//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gimnasio
{
    using System;
    using System.Collections.Generic;
    using System.Data.Entity;

    public partial class Actividad
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Actividad()
        {
            this.Entrenador_Actividad = new HashSet<Entrenador_Actividad>();
            this.Inscripcion = new HashSet<Inscripcion>();
        }
    
        public int actividad_id { get; set; }
        public string nombre { get; set; }
        public string tipo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Entrenador_Actividad> Entrenador_Actividad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inscripcion> Inscripcion { get; set; }

        public void crearActividad(string nombre,string tipo)
        {
            using (GimnasioEntities db = new GimnasioEntities())
            {
                Actividad act = new Actividad();

                act.nombre = nombre;
                act.tipo = tipo;

                db.Actividad.Add(act);
                db.SaveChanges();
            }
        }

        public void modificarActividad(int id,string nombre,string tipo)
        {
            using (GimnasioEntities db = new GimnasioEntities())
            {
                Actividad act = new Actividad();
                act = db.Actividad.Find(id);

                act.nombre = nombre;
                act.tipo = tipo;

                db.Entry(act).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
            }
        }

        public void bajaFisica(int id)
        {
            using(GimnasioEntities db = new GimnasioEntities())
            {
                Actividad act = new Actividad();
                act = db.Actividad.Find(id);

                db.Actividad.Remove(act);
                db.SaveChanges();

            }
        }

        public DbSet<Actividad> obtenerActividad()
        {
            GimnasioEntities db = new GimnasioEntities();
            return db.Actividad;
        }
    }
}
