//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gimnasio
{
    using System;
    using System.Collections.Generic;
    using System.Data.Entity;

    public partial class Cliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cliente()
        {
            this.Inscripcion = new HashSet<Inscripcion>();
            this.Registro = new HashSet<Registro>();
        }
    
        public int cliente_id { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public long dni { get; set; }
        public Nullable<System.DateTime> fecha_nac { get; set; }
        public string sexo { get; set; }
        public Nullable<bool> borrado_logico { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inscripcion> Inscripcion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Registro> Registro { get; set; }

        public void insertarCliente(string nombre,string apellido,long dni,DateTime fecha_nac,string sexo)
        {
            using (GimnasioEntities db = new GimnasioEntities())
            {
                Cliente cli = new Cliente();

                cli.nombre = nombre;
                cli.apellido = apellido;
                cli.dni = dni;
                cli.fecha_nac = fecha_nac;
                cli.sexo = sexo;
                cli.borrado_logico = false;

                db.Cliente.Add(cli);
                db.SaveChanges();
            }
        }

        public void modificarCliente(int id, string nombre, string apellido, long dni, DateTime fecha_nac, string sexo)
        {
            using (GimnasioEntities db = new GimnasioEntities())
            {
                Cliente cli = new Cliente();
                cli = db.Cliente.Find(id);

                cli.nombre = nombre;
                cli.apellido = apellido;
                cli.dni = dni;
                cli.fecha_nac = fecha_nac;
                cli.sexo = sexo;
                cli.borrado_logico = false;

                db.Entry(cli).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
            }
        }

        public void bajaLogica(int id)
        {
            using(GimnasioEntities db = new GimnasioEntities())
            {
                Cliente cli = new Cliente();
                cli = db.Cliente.Find(id);

                cli.borrado_logico = true;

                db.Entry(cli).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
            }
        }

        public void bajaFisica(int id)
        {
            using (GimnasioEntities db = new GimnasioEntities())
            {
                Cliente cli = new Cliente();
                cli = db.Cliente.Find(id);

                db.Cliente.Remove(cli);
                db.SaveChanges();
            }
        }

        public DbSet<Cliente> obtenerClientes()
        {
            GimnasioEntities db = new GimnasioEntities();
            return db.Cliente;
        }

    }
}
